// Country flag emoji mapping
export const countryFlags: Record<string, string> = {
  // Americas
  'USA': '🇺🇸',
  'United States': '🇺🇸',
  'Canada': '🇨🇦',
  'Mexico': '🇲🇽',
  'Brazil': '🇧🇷',
  'Argentina': '🇦🇷',
  'Chile': '🇨🇱',
  'Colombia': '🇨🇴',
  'Peru': '🇵🇪',
  
  // Europe
  'UK': '🇬🇧',
  'United Kingdom': '🇬🇧',
  'Germany': '🇩🇪',
  'France': '🇫🇷',
  'Italy': '🇮🇹',
  'Spain': '🇪🇸',
  'Netherlands': '🇳🇱',
  'Switzerland': '🇨🇭',
  'Sweden': '🇸🇪',
  'Norway': '🇳🇴',
  'Denmark': '🇩🇰',
  'Finland': '🇫🇮',
  'Belgium': '🇧🇪',
  'Austria': '🇦🇹',
  'Ireland': '🇮🇪',
  'Portugal': '🇵🇹',
  'Poland': '🇵🇱',
  'Czech Republic': '🇨🇿',
  'Hungary': '🇭🇺',
  'Romania': '🇷🇴',
  'Bulgaria': '🇧🇬',
  'Croatia': '🇭🇷',
  'Serbia': '🇷🇸',
  'Greece': '🇬🇷',
  'Turkey': '🇹🇷',
  'Russia': '🇷🇺',
  'Ukraine': '🇺🇦',
  'Estonia': '🇪🇪',
  'Latvia': '🇱🇻',
  'Lithuania': '🇱🇹',
  
  // Asia Pacific
  'China': '🇨🇳',
  'Japan': '🇯🇵',
  'South Korea': '🇰🇷',
  'Korea': '🇰🇷',
  'India': '🇮🇳',
  'Singapore': '🇸🇬',
  'Hong Kong': '🇭🇰',
  'Taiwan': '🇹🇼',
  'Australia': '🇦🇺',
  'New Zealand': '🇳🇿',
  'Thailand': '🇹🇭',
  'Vietnam': '🇻🇳',
  'Malaysia': '🇲🇾',
  'Indonesia': '🇮🇩',
  'Philippines': '🇵🇭',
  'Pakistan': '🇵🇰',
  'Bangladesh': '🇧🇩',
  'Sri Lanka': '🇱🇰',
  'Myanmar': '🇲🇲',
  'Cambodia': '🇰🇭',
  'Laos': '🇱🇦',
  
  // Middle East & Africa
  'UAE': '🇦🇪',
  'Saudi Arabia': '🇸🇦',
  'Qatar': '🇶🇦',
  'Kuwait': '🇰🇼',
  'Bahrain': '🇧🇭',
  'Oman': '🇴🇲',
  'Jordan': '🇯🇴',
  'Lebanon': '🇱🇧',
  'Israel': '🇮🇱',
  'Palestine': '🇵🇸',
  'Syria': '🇸🇾',
  'Iraq': '🇮🇶',
  'Iran': '🇮🇷',
  'Egypt': '🇪🇬',
  'Morocco': '🇲🇦',
  'Tunisia': '🇹🇳',
  'Algeria': '🇩🇿',
  'Libya': '🇱🇾',
  'Lybia': '🇱🇾', // Alternative spelling
  'Sudan': '🇸🇩',
  'Ethiopia': '🇪🇹',
  'Kenya': '🇰🇪',
  'Uganda': '🇺🇬',
  'Tanzania': '🇹🇿',
  'South Africa': '🇿🇦',
  'Nigeria': '🇳🇬',
  'Ghana': '🇬🇭',
  'Senegal': '🇸🇳',
  'Mauritania': '🇲🇷',
  'Mali': '🇲🇱',
  'Burkina Faso': '🇧🇫',
  'Niger': '🇳🇪',
  'Chad': '🇹🇩',
  'Cameroon': '🇨🇲',
  'Central African Republic': '🇨🇫',
  'Democratic Republic of Congo': '🇨🇩',
  'Republic of Congo': '🇨🇬',
  'Gabon': '🇬🇦',
  'Equatorial Guinea': '🇬🇶',
  'Sao Tome and Principe': '🇸🇹',
  'Rwanda': '🇷🇼',
  'Burundi': '🇧🇮',
  'Djibouti': '🇩🇯',
  'Somalia': '🇸🇴',
  'Eritrea': '🇪🇷',
  'Zimbabwe': '🇿🇼',
  'Zambia': '🇿🇲',
  'Malawi': '🇲🇼',
  'Mozambique': '🇲🇿',
  'Madagascar': '🇲🇬',
  'Mauritius': '🇲🇺',
  'Seychelles': '🇸🇨',
  'Comoros': '🇰🇲',
  'Botswana': '🇧🇼',
  'Namibia': '🇳🇦',
  'Lesotho': '🇱🇸',
  'Eswatini': '🇸🇿',
  'Angola': '🇦🇴',
  'Yemen': '🇾🇪',
  
  // Special cases
  'Global': '🌍',
  'Europe': '🇪🇺',
  'MENA': '🌍',
}

export function getCountryFlag(countryName: string): string {
  return countryFlags[countryName] || '🏳️'
}

export function getCountryName(countryName: string): string {
  // Handle special cases
  const specialCases: Record<string, string> = {
    'UAE': 'United Arab Emirates',
    'USA': 'United States',
    'UK': 'United Kingdom',
  }
  
  return specialCases[countryName] || countryName
}
