import { Button } from "@/components/ui/button";
import { Download, Edit, ArrowRight } from "lucide-react";
import { useState } from "react";
import { useRouter } from "next/navigation";

export function ButtomBar({ showValidate = true, onValidate }: { showValidate?: boolean, onValidate?: () => Promise<void> }) {
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleValidate = async () => {
    setLoading(true);
    try {
      if (onValidate) {
        await onValidate();
      }
      // After main validation, trigger SWOT analysis
      const { runSWOTAnalysis } = await import('@/services/agents');
      await runSWOTAnalysis();
    } catch (error) {
      console.error('Validation error:', error);
    }
    setLoading(false);
    router.push("/dashboard/critical-report");
  };

  const handleDownload = () => {
    // Get the summary and business idea from localStorage
    const savedSummary = localStorage.getItem('brandorb_summary');
    const savedBusinessIdea = localStorage.getItem('brandorb_business_idea');
    
    if (!savedSummary || !savedBusinessIdea) {
      console.error('No summary data found to download');
      return;
    }

    // Create the content for the download
    const content = `# Business Plan Summary

## Business Idea
${savedBusinessIdea}

## Detailed Analysis
${savedSummary}

---
Generated by BrandOrb AI on ${new Date().toLocaleDateString()}
`;

    // Create a blob and download link
    const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    // Create a temporary download link
    const link = document.createElement('a');
    link.href = url;
    link.download = `business-plan-summary-${new Date().toISOString().split('T')[0]}.md`;
    
    // Trigger the download
    document.body.appendChild(link);
    link.click();
    
    // Clean up
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  const handleEdit = () => {
    // Redirect to onboarding page to edit answers
    router.push('/onboarding');
  };

  return (
    <div className="w-full h-12 shrink-0 flex items-center gap-2 bg-surface dark:bg-surface border-t border-border transition-[width,height] ease-linear">
      <div className="flex items-center gap-2 px-4 flex-1 justify-end w-full">
        <Button variant="ghost" size="sm" onClick={handleDownload}>
          <Download className="h-4 w-4 mr-2" />
          Download
        </Button>
        <Button variant="ghost" size="sm" onClick={handleEdit}>
          <Edit className="h-4 w-4 mr-2" />
          Edit
        </Button>
        {showValidate && (
          <Button
            variant="ghost"
            size="sm"
            onClick={handleValidate}
            disabled={loading}
            className="bg-primary hover:bg-primary/90 text-white hover:text-white"
          >
            {loading ? "Validating..." : "Validate"}
            <ArrowRight className="h-4 w-4 ml-2" />
          </Button>
        )}
      </div>
    </div>
  );
}
